MPD-800: provider payments indexing
SkillsFundingAgency/das-providerpayments pull request #145
Opened 2018-01-16 10:08 UTC by kuzinator

A bunch of new indexes and other query optimisiations. This is a general exercise that is not based on current performance analysis.

2018-01-24 12:57 UTC, carlbm requested changes
Can you remove the union all and add elses to create the indexes where you disable/rebuild them

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/ddl/PeriodEnd.Transient.PaymentsDue.DDL.views.sql
>  	SELECT * FROM Staging.ApprenticeshipEarnings3
This may have functional changes. I'm not sure that the performance increase is worth the risk

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/11 PeriodEnd.PaymentsDue.PreRun.Staging.ApprenticeshipEarnings.sql
> +GO
add an else to create the index if it doesn't already exist

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/09 PeriodEnd.PaymentsDue.PreRun.Staging.LearnerPriceEpisodePerPeriod.sql
> +
Add else to create the index if it doesn't already exist

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/06 PeriodEnd.PaymentsDue.Populate.Reference.RequiredPaymentsHistory.dml.sql
> +	ALTER INDEX [IDX_PaymentsHistory_Course] ON [Reference].[RequiredPaymentsHistory] REBUILD;
Add else to create the indexes if they don't already exist

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/05 PeriodEnd.PaymentsDue.Populate.Reference.ApprenticeshipEarnings.dml.sql
> +	ALTER INDEX [IDX_Earnings_Period] ON [Reference].[ApprenticeshipDeliveryEarnings] REBUILD;
Add else to create if they indexes don't exist

2018-01-24 12:57 UTC, carlbm commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/05 PeriodEnd.PaymentsDue.Populate.Reference.ApprenticeshipEarnings.dml.sql
> +IF EXISTS (SELECT * FROM sys.indexes i JOIN sys.objects t ON i.object_id = t.object_id WHERE t.name = 'ApprenticeshipEarnings' AND i.name = 'IDX_ApprenticeshipEarnings_StartDate')
Add else to create the index

2018-01-25 07:48 UTC, chrisfoster76 commented
There needs to be a ticket on the Add&Pay board for this, otherwise this branch can't be tested or merged, and won't be in the release notes.

2018-10-05 10:14 UTC, carlbm commented
very outdated

2018-10-05 10:14 UTC, closed without merging