Dpp 1218 remove duplicate payments for programme type
SkillsFundingAgency/das-providerpayments pull request #175
Opened 2018-03-13 11:33 UTC by carlbm

There are some files re the integration tests that aren't needed, but I left them in anyway.
I've also left in the whitespace changes to make the SQL more readable

2018-03-13 11:54 UTC, tom-gough requested changes

2018-03-13 11:54 UTC, tom-gough commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/10 PeriodEnd.PaymentsDue.PreRun.Staging.ApprenticeshipEarningsRequiringPayments.sql
> -              --AND ae.LearnRefNumber = ph.LearnRefNumber
commented out code can be removed

2018-03-13 11:54 UTC, tom-gough commented on src/PeriodEnd/PaymentsDue/SFA.DAS.ProviderPayments.Calc.PaymentsDue.IntegrationTests/Issues/WhenMathsAndEnglishPaymentsAreCalculated.cs
> +        [Ignore("Harness does not support multi-period-end tests")]
why add a test and immediately ignore it?

2018-03-13 11:54 UTC, tom-gough commented on src/PeriodEnd/PaymentsDue/SFA.DAS.ProviderPayments.Calc.PaymentsDue.IntegrationTests/Issues/WhenLearnerOnAStandardHasADifferentProgType.cs
> +        [Ignore("Harness does not support multi-period-end tests")]
why add a test and immediately ignore it?

2018-03-13 11:54 UTC, tom-gough commented on src/PeriodEnd/PaymentsDue/SFA.DAS.ProviderPayments.Calc.PaymentsDue.IntegrationTests/Issues/WhenLearnerOnAStandardHasADifferentProgType.cs
> +            //TestDataHelper.CopyToDeds();
why is this commented out? what is the todo about?

2018-03-13 11:54 UTC, tom-gough commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/10 PeriodEnd.PaymentsDue.PreRun.Staging.ApprenticeshipEarningsRequiringPayments.sql
> -              --AND ae.LearnRefNumber = ph.LearnRefNumber
thought this was an addition not a removal, never mind

2018-03-13 12:45 UTC, tom-gough approved these changes

2018-03-22 14:42 UTC, satya-sanikommu commented
Functional testing is done on VMs and the fix has been verified on Shadow with R07 data by validating the results. This will be further tested on Pre-Prod for an End-To-End and on Shadow for validating results based on R08 data. Ready to merge

2018-03-22 14:42 UTC, merged