DPP-902 - addition of acceptance tests and minor change to acceptance…
SkillsFundingAgency/das-providerpayments pull request #183
Opened 2018-04-18 09:30 UTC by davehowlett

… test framework to allow both ULN and learner reference number to exist in a ULN

2018-04-18 09:38 UTC, carlbm requested changes
There are build errors

2018-04-18 09:45 UTC, davehowlett commented on src/AcceptanceTesting/SpecByExample/SFA.DAS.Payments.AcceptanceTests/TableParsers/IlrTableParser.cs
> +                    if (long.TryParse(parsedLearner.Uln, out var uln))
bloody C# 7 feature crept in! Just sorting out

2018-04-19 07:21 UTC, carlbm approved these changes

2018-04-23 13:15 UTC, satya-sanikommu commented
Review and Testing completed. No issues. Ready to merge

2018-04-23 13:16 UTC, merged