Dpp 1363 fix integration tests
SkillsFundingAgency/das-providerpayments pull request #207
Opened 2018-05-17 12:23 UTC by Pauljgraham

2018-05-17 15:07 UTC, scottywakefield commented
@Pauljgraham these integration tests are much more like acceptance tests. I'd suggest they don't serve much purpose and aren't worth maintaining. I'll be removing all existing integration tests from one of the components I'm currently working on.

2018-05-18 07:11 UTC, Pauljgraham commented
They currently aren't being used. The Only value I see in it, is it may help us understand some of the data tables in the solution and how they relate to the individual processes.

2018-05-18 08:37 UTC, scottywakefield approved these changes

2018-05-20 09:54 UTC, satya-sanikommu commented
@Pauljgraham @scottywakefield Looks like this PR has not been merged, is this still required ??

@scottywakefield You cherry picked some integration changes from a branch and merged into Develop. Are these the same changes ???

2018-05-21 14:00 UTC, scottywakefield commented
@satya-sanikommu the cherry picked changes were for DPP-1361.

2018-05-21 14:04 UTC, satya-sanikommu commented
@scottywakefield Thanks, yes just realised that. Also changed the BaseBranch to develop for these changes to go into, as TransferBaseBranch_2 has been merged into Develop and has been deleted.

2018-05-29 08:58 UTC, scottywakefield requested changes

2018-05-29 08:58 UTC, scottywakefield commented on src/PeriodEnd/LevyPayments/SFA.DAS.ProviderPayments.Calc.LevyPayments.IntegrationTests/Utilities/TestDataHelper.cs
> +            // TODO Review this. I added field names and guessed the values based on the column order. However I had to comment out 3 fields and
so we still need to sort out this comment @Pauljgraham.

2018-05-30 08:33 UTC, scottywakefield approved these changes

2018-05-30 11:37 UTC, carlbm approved these changes
All tests green now

2018-06-01 15:14 UTC, satya-sanikommu commented
Review and Testing completed. Ready to merge

2018-06-01 15:14 UTC, merged