Dpp 1283 duplicate maths and english payments
SkillsFundingAgency/das-providerpayments pull request #210
Opened 2018-05-30 08:35 UTC by davehowlett

2018-05-30 09:23 UTC, scottywakefield commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/14 PeriodEnd.PaymentsDue.PreRun.Staging.ApprenticeshipEarnings3.sql
> +        From  Reference.CollectionPeriods Where [Open] = 1)
Question: would this case statement be better as a function in sql?

2018-05-30 09:59 UTC, scottywakefield approved these changes

2018-05-31 13:39 UTC, Pauljgraham requested changes

2018-05-31 13:39 UTC, Pauljgraham commented on src/AcceptanceTesting/SpecByExample/SFA.DAS.Payments.AcceptanceTests/Features/Ilr Changes/learner_changes_contract_type.feature
> +        | Provider Earned from SFA                | 0      | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25  | 639.25 |
Provider Earned from SFA should not be offset (only payments are offset)

2018-05-31 13:39 UTC, Pauljgraham commented on src/AcceptanceTesting/SpecByExample/SFA.DAS.Payments.AcceptanceTests/Features/Ilr Changes/learner_changes_contract_type.feature
> +        | Provider Earned from SFA                | 0      | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25 | 639.25  | 639.25 |
Provider earned from SFA should not be offset. Althrough no assertion is done on this line

2018-05-31 13:39 UTC, Pauljgraham commented on src/PeriodEnd/PaymentsDue/DeployPaymentsDue/sql/dml/14 PeriodEnd.PaymentsDue.PreRun.Staging.ApprenticeshipEarnings3.sql
> +        From  Reference.CollectionPeriods Where [Open] = 1)
Could we add a comment to this so it says it's checking episode start date is in the academic year.

2018-05-31 14:31 UTC, Pauljgraham approved these changes

2018-06-04 14:21 UTC, carlbm approved these changes

2018-06-12 12:15 UTC, satya-sanikommu commented
Review and testing completed. Ready to merge

2018-06-12 12:15 UTC, merged