DPP-1467 payments history table mapping
SkillsFundingAgency/das-providerpayments pull request #273
Opened 2018-07-03 13:22 UTC by scottywakefield

2018-07-03 15:21 UTC, Pauljgraham approved these changes

2018-07-04 11:13 UTC, carlbm requested changes

2018-07-04 11:13 UTC, carlbm commented on src/PeriodEnd/Refunds/DeployRefunds/sql/ddl/PeriodEnd.Deds.Refunds.DDL.views.sql
> +IF NOT EXISTS(SELECT [schema_id] FROM sys.schemas WHERE [name]='Refunds')
You'll need to put this into a migration script

2018-07-04 13:56 UTC, scottywakefield commented
@carlbm I've moved anything deds (currently only a view) into a migration script (0036...).

2018-07-04 15:20 UTC, scottywakefield commented
Agreed to add further tables and mappings required for the rest of the refunds component

2018-07-05 06:16 UTC, carlbm approved these changes

2018-07-05 08:01 UTC, merged