Dpp 1451 new refunds summarizer for Levy Balances
SkillsFundingAgency/das-providerpayments pull request #278
Opened 2018-07-06 10:21 UTC by Pauljgraham

2018-07-06 12:55 UTC, carlbm requested changes

2018-07-06 12:55 UTC, carlbm commented on src/PeriodEnd/Refunds/SFA.DAS.ProviderPayments.Calc.Refunds/Services/SummariseAccountBalances.cs
> +        private readonly ConcurrentDictionary<long, decimal> _accountsDictionary;
_accountsDictionary to _accountLevyBalanceAdjustmentDictionary?

2018-07-06 12:55 UTC, carlbm commented on src/PeriodEnd/Refunds/SFA.DAS.ProviderPayments.Calc.Refunds/Services/SummariseAccountBalances.cs
> +            var groupsByAccountId = refunds.Where(x=>x.TransactionType == TransactionType.Learning).GroupBy(x => x.AccountId);
This should be by funding source 1 (levy) rather than transaction type 1

2018-07-06 13:50 UTC, scottywakefield commented
I'll approve once you've made the changes Carl has raised.

2018-07-09 07:28 UTC, carlbm approved these changes

2018-07-09 07:31 UTC, merged